/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API principal para el sistema de triage asistido por IA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorRFC7807
 */
export interface ErrorRFC7807 {
    /**
     * 
     */
    type: string;
    /**
     * 
     */
    titulo: string;
    /**
     * 
     */
    estatus: number;
    /**
     * 
     */
    detalles?: string | null;
    /**
     * 
     */
    instancias?: string;
    /**
     * 
     */
    traceId?: string;
}

/**
 * Check if a given object implements the ErrorRFC7807 interface.
 */
export function instanceOfErrorRFC7807(value: object): value is ErrorRFC7807 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('titulo' in value) || value['titulo'] === undefined) return false;
    if (!('estatus' in value) || value['estatus'] === undefined) return false;
    return true;
}

export function ErrorRFC7807FromJSON(json: any): ErrorRFC7807 {
    return ErrorRFC7807FromJSONTyped(json, false);
}

export function ErrorRFC7807FromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorRFC7807 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'titulo': json['titulo'],
        'estatus': json['estatus'],
        'detalles': json['detalles'] === undefined ? undefined : json['detalles'] === null ? null : json['detalles'],
        'instancias': json['instancias'] == null ? undefined : json['instancias'],
        'traceId': json['trace_id'] == null ? undefined : json['trace_id'],
    };
}

export function ErrorRFC7807ToJSON(json: any): ErrorRFC7807 {
    return ErrorRFC7807ToJSONTyped(json, false);
}

export function ErrorRFC7807ToJSONTyped(value?: ErrorRFC7807 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'titulo': value['titulo'],
        'estatus': value['estatus'],
        'detalles': value['detalles'],
        'instancias': value['instancias'],
        'trace_id': value['traceId'],
    };
}

