/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API principal para el sistema de triage asistido por IA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TriageOutput } from './TriageOutput';
import {
    TriageOutputFromJSON,
    TriageOutputFromJSONTyped,
    TriageOutputToJSON,
    TriageOutputToJSONTyped,
} from './TriageOutput';

/**
 * 
 * @export
 * @interface PatientHistory
 */
export interface PatientHistory {
    /**
     * 
     */
    patientId?: string;
    /**
     * 
     */
    records?: Array<TriageOutput>;
}

/**
 * Check if a given object implements the PatientHistory interface.
 */
export function instanceOfPatientHistory(value: object): value is PatientHistory {
    return true;
}

export function PatientHistoryFromJSON(json: any): PatientHistory {
    return PatientHistoryFromJSONTyped(json, false);
}

export function PatientHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatientHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'patientId': json['patientId'] == null ? undefined : json['patientId'],
        'records': json['records'] == null ? undefined : ((json['records'] as Array<any>).map(TriageOutputFromJSON)),
    };
}

export function PatientHistoryToJSON(json: any): PatientHistory {
    return PatientHistoryToJSONTyped(json, false);
}

export function PatientHistoryToJSONTyped(value?: PatientHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patientId': value['patientId'],
        'records': value['records'] == null ? undefined : ((value['records'] as Array<any>).map(TriageOutputToJSON)),
    };
}

