/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API principal para el sistema de triage asistido por IA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface TriageOutput
 */
export interface TriageOutput {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    pacienterut?: string;
    /**
     * 
     */
    esiLevel?: number;
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    fecha?: Date;
}

/**
 * Check if a given object implements the TriageOutput interface.
 */
export function instanceOfTriageOutput(value: object): value is TriageOutput {
    return true;
}

export function TriageOutputFromJSON(json: any): TriageOutput {
    return TriageOutputFromJSONTyped(json, false);
}

export function TriageOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriageOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'pacienterut': json['pacienterut'] == null ? undefined : json['pacienterut'],
        'esiLevel': json['esiLevel'] == null ? undefined : json['esiLevel'],
        'status': json['status'] == null ? undefined : json['status'],
        'fecha': json['fecha'] == null ? undefined : (parseDateTime(json['fecha'])),
    };
}

export function TriageOutputToJSON(json: any): TriageOutput {
    return TriageOutputToJSONTyped(json, false);
}

export function TriageOutputToJSONTyped(value?: TriageOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'pacienterut': value['pacienterut'],
        'esiLevel': value['esiLevel'],
        'status': value['status'],
        'fecha': value['fecha'] == null ? value['fecha'] : serializeDateTime(value['fecha']),
    };
}

