/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API principal para el sistema de triage asistido por IA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriageInputSignosVitales
 */
export interface TriageInputSignosVitales {
    /**
     * 
     */
    pulsaciones?: number;
    /**
     * 
     */
    presionSanguinea?: string;
}

/**
 * Check if a given object implements the TriageInputSignosVitales interface.
 */
export function instanceOfTriageInputSignosVitales(value: object): value is TriageInputSignosVitales {
    return true;
}

export function TriageInputSignosVitalesFromJSON(json: any): TriageInputSignosVitales {
    return TriageInputSignosVitalesFromJSONTyped(json, false);
}

export function TriageInputSignosVitalesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriageInputSignosVitales {
    if (json == null) {
        return json;
    }
    return {
        
        'pulsaciones': json['Pulsaciones'] == null ? undefined : json['Pulsaciones'],
        'presionSanguinea': json['PresionSanguinea'] == null ? undefined : json['PresionSanguinea'],
    };
}

export function TriageInputSignosVitalesToJSON(json: any): TriageInputSignosVitales {
    return TriageInputSignosVitalesToJSONTyped(json, false);
}

export function TriageInputSignosVitalesToJSONTyped(value?: TriageInputSignosVitales | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Pulsaciones': value['pulsaciones'],
        'PresionSanguinea': value['presionSanguinea'],
    };
}

