/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API principal para el sistema de triage asistido por IA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TriageInputSignosVitales } from './TriageInputSignosVitales';
import {
    TriageInputSignosVitalesFromJSON,
    TriageInputSignosVitalesFromJSONTyped,
    TriageInputSignosVitalesToJSON,
    TriageInputSignosVitalesToJSONTyped,
} from './TriageInputSignosVitales';

/**
 * 
 * @export
 * @interface TriageInput
 */
export interface TriageInput {
    /**
     * 
     */
    rUT: string;
    /**
     * 
     */
    sintomas: string;
    /**
     * 
     */
    signosVitales?: TriageInputSignosVitales;
}

/**
 * Check if a given object implements the TriageInput interface.
 */
export function instanceOfTriageInput(value: object): value is TriageInput {
    if ((!('rUT' in (value as Record<string, any>)) && !('RUT' in (value as Record<string, any>))) || ((value as Record<string, any>)['rUT'] === undefined && (value as Record<string, any>)['RUT'] === undefined)) return false;
    if ((!('sintomas' in (value as Record<string, any>)) && !('Sintomas' in (value as Record<string, any>))) || ((value as Record<string, any>)['sintomas'] === undefined && (value as Record<string, any>)['Sintomas'] === undefined)) return false;
    return true;
}

export function TriageInputFromJSON(json: any): TriageInput {
    return TriageInputFromJSONTyped(json, false);
}

export function TriageInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriageInput {
    if (json == null) {
        return json;
    }
    return {
        
        'rUT': json['RUT'],
        'sintomas': json['Sintomas'],
        'signosVitales': json['SignosVitales'] == null ? undefined : TriageInputSignosVitalesFromJSON(json['SignosVitales']),
    };
}

export function TriageInputToJSON(json: any): TriageInput {
    return TriageInputToJSONTyped(json, false);
}

export function TriageInputToJSONTyped(value?: TriageInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'RUT': value['rUT'],
        'Sintomas': value['sintomas'],
        'SignosVitales': TriageInputSignosVitalesToJSON(value['signosVitales']),
    };
}

