/* tslint:disable */
/* eslint-disable */
/**
 * MediTriage API
 * API principal para el sistema de triage asistido por IA.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateUserRequest,
    CreateUserRequestFromJSON,
    CreateUserRequestToJSON,
} from '../models/CreateUserRequest';
import {
    type ErrorRFC7807,
    ErrorRFC7807FromJSON,
    ErrorRFC7807ToJSON,
} from '../models/ErrorRFC7807';
import {
    type PatientHistory,
    PatientHistoryFromJSON,
    PatientHistoryToJSON,
} from '../models/PatientHistory';
import {
    type TriageInput,
    TriageInputFromJSON,
    TriageInputToJSON,
} from '../models/TriageInput';
import {
    type TriageOutput,
    TriageOutputFromJSON,
    TriageOutputToJSON,
} from '../models/TriageOutput';

export interface CreateTriageRecordRequest {
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    triageInput: TriageInput;
}

export interface CreateUserOperationRequest {
    /**
     * 
     */
    createUserRequest: CreateUserRequest;
}

export interface GetPatientHistoryRequest {
    /**
     * 
     */
    patientId: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for createTriageRecord without sending the request
     */
    async createTriageRecordRequestOpts(requestParameters: CreateTriageRecordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createTriageRecord().'
            );
        }

        if (requestParameters['triageInput'] == null) {
            throw new runtime.RequiredError(
                'triageInput',
                'Required parameter "triageInput" was null or undefined when calling createTriageRecord().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/triage`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriageInputToJSON(requestParameters['triageInput']),
        };
    }

    /**
     * Registrar síntomas del paciente (US-01)
     */
    async createTriageRecordRaw(requestParameters: CreateTriageRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriageOutput>> {
        const requestOptions = await this.createTriageRecordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriageOutputFromJSON(jsonValue));
    }

    /**
     * Registrar síntomas del paciente (US-01)
     */
    async createTriageRecord(requestParameters: CreateTriageRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriageOutput> {
        const response = await this.createTriageRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createUser without sending the request
     */
    async createUserRequestOpts(requestParameters: CreateUserOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createUserRequest'] == null) {
            throw new runtime.RequiredError(
                'createUserRequest',
                'Required parameter "createUserRequest" was null or undefined when calling createUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/admin/users`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserRequestToJSON(requestParameters['createUserRequest']),
        };
    }

    /**
     * Gestión de usuarios y permisos (US-05)
     */
    async createUserRaw(requestParameters: CreateUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Gestión de usuarios y permisos (US-05)
     */
    async createUser(requestParameters: CreateUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createUserRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAuditLogs without sending the request
     */
    async getAuditLogsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/audit/logs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Auditoría de registros clínicos (US-04)
     */
    async getAuditLogsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        const requestOptions = await this.getAuditLogsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Auditoría de registros clínicos (US-04)
     */
    async getAuditLogs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.getAuditLogsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPatientHistory without sending the request
     */
    async getPatientHistoryRequestOpts(requestParameters: GetPatientHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['patientId'] == null) {
            throw new runtime.RequiredError(
                'patientId',
                'Required parameter "patientId" was null or undefined when calling getPatientHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/patients/{patientId}/history`;
        urlPath = urlPath.replace('{patientId}', encodeURIComponent(String(requestParameters['patientId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Consultar historial clínico (US-03)
     */
    async getPatientHistoryRaw(requestParameters: GetPatientHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PatientHistory>> {
        const requestOptions = await this.getPatientHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PatientHistoryFromJSON(jsonValue));
    }

    /**
     * Consultar historial clínico (US-03)
     */
    async getPatientHistory(requestParameters: GetPatientHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PatientHistory> {
        const response = await this.getPatientHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTriageQueue without sending the request
     */
    async getTriageQueueRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/triage/queue`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Visualizar cola de prioridad de pacientes (US-02)
     */
    async getTriageQueueRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TriageOutput>>> {
        const requestOptions = await this.getTriageQueueRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TriageOutputFromJSON));
    }

    /**
     * Visualizar cola de prioridad de pacientes (US-02)
     */
    async getTriageQueue(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TriageOutput>> {
        const response = await this.getTriageQueueRaw(initOverrides);
        return await response.value();
    }

}
